PRINT "Testing known good AREA structures"
INCLUDE ~%MOD_FOLDER%/tests/valid/are.tpa~

PRINT "Testing known good CRE structures"
INCLUDE ~%MOD_FOLDER%/tests/valid/cre.tpa~

PRINT "Testing known good ITM structures"
INCLUDE ~%MOD_FOLDER%/tests/valid/itm.tpa~

PRINT "Testing known good SPL structures"
INCLUDE ~%MOD_FOLDER%/tests/valid/spl.tpa~

PRINT "Testing known good STOR structures"
INCLUDE ~%MOD_FOLDER%/tests/valid/sto.tpa~
