DEFINE_ACTION_FUNCTION fl#valid_tests#tests#valid#cre
  RET
    success
    fail
    failed_validity_tests
BEGIN
  OUTER_SPRINT file_root "%MOD_FOLDER%/tests/valid/cre"

  ACTION_DEFINE_ASSOCIATIVE_ARRAY valid#cre BEGIN
   "crev10" => "Plain CRE V1.0 created by NI v1.36-20151216"
   "crev12" => "Plain CRE V1.2 created by WeiDU 238.02"
   "crev22" => "Plain CRE V2.2 created by WeiDU 238.02"
   "crev90" => "Plain CRE V9.0 created by WeiDU 238.02"
  END

  ACTION_PHP_EACH valid#cre AS file => desc BEGIN
    LAF test_valid
      STR_VAR
        file = EVAL "%file_root%/%file%.cre"
        desc
      RET
        success
        fail
        failed_validity_tests
    END
  END
END

LAF fl#valid_tests#tests#valid#cre RET success fail failed_validity_tests END
