DEFINE_ACTION_FUNCTION fl#valid_tests#tests#valid#itm
  RET
    success
    fail
    failed_validity_tests
BEGIN
  OUTER_SPRINT file_root "%MOD_FOLDER%/tests/valid/itm"

  ACTION_DEFINE_ASSOCIATIVE_ARRAY valid#itm BEGIN
    "itmv1" => "Plain ITM V1 created by NI v1.36-20151216"
    "itmv11" => "Plain ITM V1.1 created by WeiDU, commit 1d19c83c"
    "itmv20" => "Plain ITM V2.0 created by WeiDU 238.02"
    "itmv1a1" => "ITM V1 with 1 ability, created by NI v1.36-20151216"
    "itmv1a2" => "ITM V1 with 1 ability, located before effects, and 1 extended effect, created by NI v1.36-20151216"
    "ring39" => "Ring of Gaxx, BG2 Fixpack V11, alpha 1"
    "00ring70" => "ITM V2.0 IWD2 Petrification Protection Ring"
    "ogien" => "ITM V1 IWD Ogien's Scale"
    "bell" => "ITM V1.1 PST Bell's Shield"
  END

  ACTION_PHP_EACH valid#itm AS file => desc BEGIN
    LAF test_valid
      STR_VAR
        file = EVAL "%file_root%/%file%.itm"
        desc
      RET
        success
        fail
        failed_validity_tests
    END
  END
END

LAF fl#valid_tests#tests#valid#itm RET success fail failed_validity_tests END
