DEFINE_ACTION_FUNCTION fl#valid_tests#tests#valid#spl
  RET
    success
    fail
BEGIN
  OUTER_SPRINT file_root "%MOD_FOLDER%/tests/valid/spl"

  ACTION_DEFINE_ASSOCIATIVE_ARRAY valid#spl BEGIN
    "plain" => "Plain SPL created by NI"
  END

  ACTION_PHP_EACH valid#spl AS file => desc BEGIN
    LAF test_valid STR_VAR file = EVAL "%file_root%/%file%.spl" desc RET success fail END
  END
END

LAF fl#valid_tests#tests#valid#spl RET success fail END
